name: Test

on: 
  push:
    branches: 
      - "*"

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1.1.0

      - name: Install Porter
        id: install_porter
        uses: ./
